### PR TITLE
Evaluate torch model to get output dimension

### LINKED ISSUE #165: Don't rely on `out_features` to get output dimension of PytorchModel
`out_features` is only defined for linear layers (or, at least, it's not defined for sigmoid layers). MWE:
```python
# model.py
import torch
nn = torch.nn.Sequential(torch.nn.Linear(1, 10), torch.nn.Sigmoid())
torch.save(nn, "sigmoid_output.pt")
```
```julia
# model.jl
import MathOptAI
import PythonCall
import JuMP

nn = MathOptAI.PytorchModel("sigmoid_output.pt")
gb = MathOptAI.GrayBox(nn)
model = JuMP.Model()
JuMP.@variable(model, x)
MathOptAI.add_predictor(model, gb, [x])
```
Fails with: `ERROR: LoadError: Python: AttributeError: 'Sigmoid' object has no attribute 'out_features'`

### PR DESCRIPTION
**Pull request by Robbybp**
An attempt to fix #165. The alternative would be to search for the last linear layer, then if no linear layers exist, use the input dimension.

### CODE REVIEW

File: ext/MathOptAIPythonCallExt.jl [hunk 1]
```diff
@@ -151,9 +151,13 @@ function MathOptAI.GrayBox(
...
     H = torch.func.hessian(torch_model)
-    # TODO(odow): I'm not sure if there is a better way to get the output
-    # dimension of a torch model object?
-    output_size(::Any) = PythonCall.pyconvert(Int, torch_model[-1].out_features)
+    function output_size(x::Vector)
+        # Get the output size by passing a zero vector through the torch model.
+        # We do this instead of `torch_model[-1].out_features` as the last layer
+        # may not support out_features.
+        z = torch.zeros(length(x))
+        return PythonCall.pyconvert(Int, PythonCall.pybuiltins.len(torch_model(z)))
```
Comment (odow) [inline ext/MathOptAIPythonCallExt.jl:159]: ChatGPT agrees that this is the recommended way to get the output dimension.
```suggestion
        y = torch_model(z)
        return PythonCall.pyconvert(Int, PythonCall.pybuiltins.len(y))
```

**Review by odow — APPROVED** [review]
